name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQubeScan:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Step to Install SonarQube Scanner
      - name: Install SonarQube Scanner
        run: |
          choco install sonarqube-scanner

      # Step to Run SonarQube Scanner
      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}  # Ensure this is set up in GitHub Secrets
        run: |
          sonar-scanner -Dsonar.projectKey=GithubDemo \
                         -Dsonar.sources=. \
                         -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }}  # Ensure this points to your SonarQube URL
                         -Dsonar.login=${{ secrets.SONAR_TOKEN }}
