name: SonarQube Analysis

on:
  push:
    branches:
      - main

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'  # Use your preferred Node.js version

      - name: Install SonarScanner
        run: |
          npm install -g sonarqube-scanner

      - name: Run SonarQube Analysis
        run: |
          sonar-scanner \
          -Dsonar.projectKey=Gitdemo \
          -Dsonar.sources=. \
          -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
          -Dsonar.login=${{ secrets.SONAR_TOKEN }}
