name: SonarQube Analysis

on:
  push:
    branches:
      - main  # or master, depending on your branch name
  pull_request:
    branches:
      - main  # or master

jobs:
  sonarQubeScan:
    name: Run SonarQube Scan
    runs-on: windows-latest  # You can use windows-latest if you're using Windows runners

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: SonarQube Scan
      uses: sonarsource/sonarcloud-github-action@v1
      with:
        sonar-token: ${{ secrets.SONAR_TOKEN }}  # Store your SonarQube token in GitHub secrets
